### ISSUE TITLE
Filament Tracking Improvements

### ISSUE THREAD

**Issue by joeycortez42** [OctoFarm/OctoFarm#1324]
### OctoFarm Version

1.7.3

### OctoPrint Version(s)

1.8.6

### pm2 or docker?

docker

### Operating System

Mac OS

### Description of the problem

I am trying to migrate away from the Filament Manager plugin since support has been dropped. But I noticed some issues with using OctoFarms built-in filament tracking.

- [ ] List View: Tool 0: Alphabetical sorting of spools in dropdown. Currently sorts by creation index.
- [ ] Filament View: Alphabetical sorting of spools. Currently sorts by creation index.
- [ ] Filament View: Profile Manager: Alphabetical sorting of profiles. Currently sorts by creation index.
- [ ] Filament View: Spool Manager: Rename "Used (g)" column to "Remaining (g)"
- [ ] Filament View: Spool Manager: Changes to spool data like "Used (g)" field not always saved. Sometimes duplicate sets of spools appear in the view but are gone after a page refresh.
- [ ] Filament View: Spool data is inaccurate or miscalculated. Data seems like some spools are calculated by filament used and others are calculated by filament remaining.

### Steps taken to reproduce

Use OctoFarm Filament tracking.

[octofarm_dump-10-19-2022-9-17-05 AM.zip](https://github.com/OctoFarm/OctoFarm/files/9820793/octofarm_dump-10-19-2022-9-17-05.AM.zip)

![Screen Shot 2022-10-19 at 9 18 19 AM](https://user-images.githubusercontent.com/1263913/196702152-cc0f64a9-4e2f-4f8c-8fed-2111b70b302c.png)
