### ISSUE TITLE
1.2-RC1 Feedback / Bug Reports

### ISSUE THREAD

**Issue by NotExpectedYet** [OctoFarm/OctoFarm#665]
Please leave any feedback / bug reports for version 1.2-RC1 below. 

_New Bugs:_ 
- [x] #667
- [x] #668
- [x] #670 
- [x] #656

_Historical:_
- [x] #605 having no spool selected shows `null` instead of `No Spool`
- [x] #606 Expected units total is displaying 0 with spool selected
- [ ] #607 Allow Current User to be saved in database / Editable in UI
- [ ] #615 Refactor the printer settings saving flow
- [ ] #617 Resyncing printer shows "Shutdown" shortly
- [ ] #618 Root cause not yet found/fixed (file property exception of job which is incorrectly null)
- [ ] #624 MongoDB Error saving farmPrinter in trackCounters after printer creation
- [x] #625 Template printer management wrong closing/opening of tags
- [ ] #548 printer management table is not looking to good (wrapping)
- [ ] #538 Filament / History Graphs stay "loading..." when no data presented if outside 30 day window
- [ ] #536 Client is too slow to respond to server restart, iAmAlive check comes back too quick
- [x] #388 Completely Depricate Wiki and move over to website (or whats left of it)
- [ ] #374 Couple server port to .env and ditch serverSettings prop

_Expected Features:_
- [x] #526
- [ ] #329
- [ ] #299
- [ ] #295
- [ ] #291
